//*** Generated By ElementalBuilder ***//

using FluentValidation;
using System;
using System.Collections.Generic;
using System.Text;

namespace Elementalist.Core.CrossCuttingConserns.Validation
{
    public static class ValidationTool
    {
        public static void Validate(IValidator validator,object entity)//Burada IEntity de olur ama DTO lar uygulamak istersek diye object sectim.
        {
            var result = validator.Validate(entity);
            if (!result.IsValid)
                throw new ValidationException(result.Errors);
        }
    }
}
